# Generated by Django 4.2.1 on 2025-07-21 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_route',
            name='train_class',
            field=models.CharField(choices=[('1AC', 'First AC'), ('2AC', 'Second AC'), ('3AC', 'Third AC'), ('SL', 'Sleeper')], default='SL', max_length=20),
        ),
    ]
