# Generated by Django 4.2.1 on 2025-07-21 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0002_add_route_train_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_route',
            name='train_class',
        ),
    ]
